quarkus:
  grpc:
    server:
      port: 9000

  datasource:
    db-kind: postgresql
#    jdbc:
#      url: jdbc:postgresql://${DB_HOST:192.168.1.20}:5432/cvdb
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    reactive:
      url: postgresql://${DB_HOST:171.229.223.206}:5432/cvdb

